film/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path("", views.FilmList.as_view(), name='home'),
    path('<slug:slug>/', views.film_detail, name='film_detail'),
    path(
        '<slug:slug>/edit_review/<int:review_id>',
        views.review_edit, name='review_edit'),
    path(
        '<slug:slug>/delete_review/<int:review_id>',
        views.review_delete, name='review_delete'),
]

film_club/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path("post/", include("post.urls"), name="post-urls"),
    path('summernote/', include('django_summernote.urls')),
    path("", include("film.urls"), name="film-urls"),
]

film/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from cloudinary.models import CloudinaryField
import datetime
import uuid

STATUS = ((0, "Draft"), (1, "Published"))

GENRE_CHOICES = (
    ('horror', 'HORROR'),
    ('drama', 'DRAMA'),
    ('action', 'ACTION'),
    ('comedy', 'COMEDY'),
    ('sci-fi', 'SCI-FI'),
    ('western', 'WESTERN'),
    ('thriller', 'THRILLER'),
    ('documentary', 'DOCUMENTARY'),
    ('fantasy', 'FANTASY'),
    ('romance', 'ROMANCE'),
    ('crime', 'CRIME'),
)


class Movie(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, default=uuid.uuid4)
    year = models.IntegerField(('year'), default=datetime.datetime.now().year)
    genre = models.CharField(
        max_length=15, choices=GENRE_CHOICES, default='horror')
    featured_image = CloudinaryField('image', default='placeholder')
    synopsis = models.TextField()
    director = models.CharField(max_length=200, unique=False)
    added_on = models.DateTimeField(auto_now_add=True)

    # Generate the slug based on title and id
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:50]
            if self.id:
                self.slug += '-' + str(self.id)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-added_on"]

    def __str__(self):
        return f"{self.title} | {self.year}"


class Review(models.Model):
    title = models.CharField(max_length=200)
    film = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="reviews")
    slug = models.SlugField(max_length=200, unique=True, null=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="review_author")
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} | by {self.author}"

film/forms.py
from .models import Review
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content',)

    def __init__(self, *args, **kwargs):
        self.film = kwargs.pop('film', None)
        super().__init__(*args, **kwargs)

film/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Movie, Review
from .forms import ReviewForm
from post.forms import FilmForm


class FilmList(generic.ListView):
    queryset = Movie.objects.all()
    template_name = "film/index.html"
    paginate_by = 3


# Post reviews
def film_detail(request, slug):
    queryset = Movie.objects.all()
    film = get_object_or_404(queryset, slug=slug)
    reviews = film.reviews.all().order_by("-created_on")
    review_count = film.reviews.filter().count()

    if request.method == "POST":
        review_form = ReviewForm(data=request.POST, film=film)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.author = request.user
            review.film = film
            review.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Review submitted.'
            )
            return HttpResponseRedirect(reverse('film_detail', args=[slug]))
        else:
            for error in review_form.errors.values():
                messages.add_message(request, messages.ERROR, error)
    else:
        review_form = ReviewForm(film=film)

    return render(
        request,
        "film/film_detail.html",
        {
            "film": film,
            "review": reviews,
            "review_count": review_count,
            "review_form": review_form,
        },
    )


# Edit reviews
def review_edit(request, slug, review_id):
    """
    view to edit reviews
    """
    if request.method == "POST":

        queryset = Movie.objects.all()
        film = get_object_or_404(queryset, slug=slug)
        review = get_object_or_404(Review, pk=review_id)
        review_form = ReviewForm(data=request.POST, instance=review)

        if review_form.is_valid() and review.author == request.user:
            review = review_form.save(commit=False)
            review.film = film
            review.save()
            messages.add_message(request, messages.SUCCESS, 'Review Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating review!')

    return HttpResponseRedirect(reverse('film_detail', args=[slug]))


# Delete reviews
def review_delete(request, slug, review_id):
    """
    view to delete reviews
    """
    queryset = Movie.objects.all()
    film = get_object_or_404(queryset, slug=slug)
    review = get_object_or_404(Review, pk=review_id)

    if review.author == request.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS, 'Review deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own reviews!')

    return HttpResponseRedirect(reverse('film_detail', args=[slug]))

film/templates/film/film_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container card film-card">
    <div class="col-md-12 pt-4">
      <h1 class="film-title mb-3">{{ film.title }}</h1>
      <p class="film-subtitle">{{ film.genre }} | {{ film.year }}</p>
      <p class="card-text mt-3">{{ film.synopsis | safe }}</p>
      <p> Director: {{ film.director }}</p>
      <!--Need if no image is uploaded-->
    </div>
    {% if "placeholder" in film.featured_image.url %}
    <img src="{% static 'images/default.jpg' %}" alt="placeholder image">
    {% else %}
    <img src="{{ film.featured_image.url }}" alt="{{ film.title }}">
    {% endif %}
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mt-3 mb-5 review-card">
      <!-- Display count of reviews -->
      <strong class="r-count">
        <i class="far fa-comments"></i> {{ review_count }}
      </strong>
      <!-- Display Reviews -->
      <h4>Reviews:</h4>
      <div class="card-body ">
        <!-- Loop through reviews -->
        {% for review in review %}
        <div class="p-2 reviews mb-5">
          <h3 id="title{{ review.id }}">{{ review.title }}</h3>
          <div id="review{{ review.id }}">
            {{ review.content | safe }}
          </div>
          <br>
          <h5>by {{ review.author }}</h5>
          {{ review.created_on }}
          <!--delete & edit reviews-->
          {% if user.is_authenticated and review.author == user %}
          <button class="btn btn-delete btn-sm" review_id="{{ review.id }}">Delete</button>
          <button class="btn btn-edit btn-sm" review_id="{{ review.id }}">Edit</button>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>

    <!-- new review form -->
    <div class="col-md-4 card mt-3 mb-5 new-rev">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h4>Post your review on the film:</h4>
        <p>Posting as: {{ user.username }}</p>

        <!-- Display messages -->
        {% if messages %}
        <div>
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <form id="reviewForm" method="POST" style="margin-top: 1.3em;">
          {{ review_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-signup btn-md">Submit</button>
        </form>
        {% else %}
        <p>Log in to leave a review</p>
        {% endif %}
      </div>
    </div>
  </div>  
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        This review will be deleted permanently. Are you sure you want to delete the review?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/reviews.js'  %}"></script>
{% endblock %}

film/templates/film/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">
        <div class="banner">
            <div class="cover-text">
                <h1>Welcome to django's.film-club</h1>
                <h5 class="tag">The 'd' is silent</h5>
                <p>We are a tribe of movie lovers! Anyone can join our community in watching and reviewing the weekly films
                    subjects and share your opinions who share your passion.
                </p>
                <a class="film-button" href="#film-catalogue">
                    <p>Film Catalogue</p>
                </a>
            </div>
        </div>

        <!-- Movies Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row" id="film-catalogue">
                {% for movie in movie_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body film-cat">
                            <div class="image-container">
                                <div class="film-img">
                                    {% if "placeholder" in movie.featured_image.url %}
                                    <img class="card-img-top film-img" src="{% static 'images/default.jpg' %}" alt="placeholder image">
                                    {% else %}
                                    <img class="card-img-top" src="{{ movie.featured_image.url }}" alt="{{ movie.title }}">
                                    {% endif %}
                                </div>
                                <div class="image-flash">
                                    <p class="year">{{ movie.year }} | {{ movie.genre }}</p>
                                </div>
                            </div>
                            <a href="{% url 'film_detail' movie.slug %}" class="post-link">
                                <h2 class="card-title mt-3">{{ movie.title }}</h2>
                                <p class="card-text synopsis">{{ movie.synopsis | safe }}</p>
                            </a>
                            <hr>
                            <p class="card-text text-muted h6 date">{{ movie.added_on }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
            </li>
            {% endif %}

            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}